# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.apartments.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     MyBnB.Repo.insert!(%MyBnB.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias MyBnB.Repo
alias MyBnB.Apartments
alias MyBnB.Apartments.Apartment

json_examples = """
[
  {
    "name": "Central Park View Loft",
    "headline": "Stunning views in the heart of NYC!",
    "description": "A cozy and modern loft with a direct view of Central Park. Close to all major attractions and subway stations.",
    "address": "123 Manhattan St.",
    "city": "New York",
    "zip": "10001",
    "state": "NY",
    "latitude": 40.785091,
    "longitude": -73.968285,
    "amount": 20050,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "LA Luxury Condo",
    "headline": "Experience Hollywood Glam in a Condo!",
    "description": "A luxurious condo located minutes away from the Hollywood Walk of Fame. Enjoy sunsets from the balcony.",
    "address": "456 Hollywood Blvd.",
    "city": "Los Angeles",
    "zip": "90028",
    "state": "CA",
    "latitude": 34.052235,
    "longitude": -118.243683,
    "amount": 23000,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Miami Beach Front",
    "headline": "Relax with the Waves!",
    "description": "A beachfront apartment with stunning views and direct access to the beach.",
    "address": "789 Ocean Dr.",
    "city": "Miami",
    "zip": "33139",
    "state": "FL",
    "latitude": 25.790654,
    "longitude": -80.130045,
    "amount": 18000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Austin Downtown Studio",
    "headline": "Enjoy the Best of Austin!",
    "description": "Stay in the heart of Austin with walking distance to restaurants, nightlife, and more.",
    "address": "101 Austin Ave.",
    "city": "Austin",
    "zip": "78701",
    "state": "TX",
    "latitude": 30.267153,
    "longitude": -97.743057,
    "amount": 12000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 0,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Seattle Skyview Apartment",
    "headline": "Views of the Space Needle!",
    "description": "Modern apartment located centrally with great views of downtown Seattle.",
    "address": "234 Pike St.",
    "city": "Seattle",
    "zip": "98101",
    "state": "WA",
    "latitude": 47.6097,
    "longitude": -122.3331,
    "amount": 15000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "New Orleans Jazz Suite",
    "headline": "Experience the Heartbeat of NOLA!",
    "description": "Stay right in the midst of all the music, food, and culture New Orleans has to offer.",
    "address": "567 Bourbon St.",
    "city": "New Orleans",
    "zip": "70116",
    "state": "LA",
    "latitude": 29.951065,
    "longitude": -90.071533,
    "amount": 17000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Brooklyn Brownstone",
    "headline": "Classic NY Living",
    "description": "Experience classic Brooklyn in this historic brownstone, close to parks and cafes.",
    "address": "321 Brooklyn Ave.",
    "city": "New York",
    "zip": "11213",
    "state": "NY",
    "latitude": 40.678178,
    "longitude": -73.944158,
    "amount": 19500,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 3,
    "beds_count": 3,
    "bathrooms_count": 1
  },
  {
    "name": "Santa Monica Beach House",
    "headline": "Steps from the Beach!",
    "description": "Stay at our classic beach house and enjoy morning walks along the Santa Monica beach.",
    "address": "890 Santa Monica Blvd.",
    "city": "Los Angeles",
    "zip": "90401",
    "state": "CA",
    "latitude": 34.0522,
    "longitude": -118.2437,
    "amount": 22000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 2
  },
  {
    "name": "South Beach Villa",
    "headline": "Luxury Living in Miami",
    "description": "Enjoy the Miami lifestyle in our luxury villa, complete with a private pool.",
    "address": "1020 Alton Rd.",
    "city": "Miami",
    "zip": "33139",
    "state": "FL",
    "latitude": 25.790654,
    "longitude": -80.134024,
    "amount": 45000,
    "currency": "USD",
    "guests_count": 8,
    "bedrooms_count": 4,
    "beds_count": 5,
    "bathrooms_count": 3
  },
  {
    "name": "Historic Seattle Cottage",
    "headline": "Charm in the Heart of the City",
    "description": "Stay in our beautifully preserved historic cottage. Close to Pike Place and other attractions.",
    "address": "456 Market St.",
    "city": "Seattle",
    "zip": "98107",
    "state": "WA",
    "latitude": 47.6062,
    "longitude": -122.3321,
    "amount": 13500,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "Chic Loft in Downtown LA",
    "headline": "Modern Design in the Heart of the City",
    "description": "Relax in this chic loft space, complete with a rooftop pool and views of the LA skyline.",
    "address": "1010 Broadway St.",
    "city": "Los Angeles",
    "zip": "90015",
    "state": "CA",
    "latitude": 34.040713,
    "longitude": -118.246769,
    "amount": 21000,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 1,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "Hill Country Retreat in Austin",
    "headline": "Escape to Nature",
    "description": "This spacious home offers a serene escape in the Texas Hill Country, but it's just a short drive to downtown Austin.",
    "address": "4321 Hilltop Dr.",
    "city": "Austin",
    "zip": "78746",
    "state": "TX",
    "latitude": 30.296171,
    "longitude": -97.827567,
    "amount": 30000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 2
  },
  {
    "name": "Art Deco Apartment in Miami",
    "headline": "Historical Charm with Modern Amenities",
    "description": "Enjoy this beautifully restored Art Deco apartment in the heart of South Beach.",
    "address": "1515 Collins Ave.",
    "city": "Miami",
    "zip": "33140",
    "state": "FL",
    "latitude": 25.792920,
    "longitude": -80.135301,
    "amount": 19000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 2
  },
  {
    "name": "Cozy Seattle Houseboat",
    "headline": "Unique Waterfront Experience",
    "description": "Stay on this charming houseboat and enjoy the beauty of Seattle from the water!",
    "address": "99 Lake Union Blvd.",
    "city": "Seattle",
    "zip": "98109",
    "state": "WA",
    "latitude": 47.6298,
    "longitude": -122.3336,
    "amount": 17500,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "French Quarter Mansion",
    "headline": "Historic Beauty in NOLA",
    "description": "Experience the magic of New Orleans in this historic mansion located in the heart of the French Quarter.",
    "address": "202 Royal St.",
    "city": "New Orleans",
    "zip": "70130",
    "state": "LA",
    "latitude": 29.954648,
    "longitude": -90.070561,
    "amount": 45000,
    "currency": "USD",
    "guests_count": 6,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 3
  },
  {
    "name": "Modern Condo with Empire State Views",
    "headline": "Iconic NYC Views",
    "description": "Located in Midtown, this condo offers stunning views of the Empire State Building.",
    "address": "505 5th Ave.",
    "city": "New York",
    "zip": "10018",
    "state": "NY",
    "latitude": 40.753899,
    "longitude": -73.981762,
    "amount": 25000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Venice Beach Studio",
    "headline": "Surfer's Paradise",
    "description": "Just steps from Venice Beach, this cozy studio is perfect for a beach getaway.",
    "address": "3030 Ocean Front Walk",
    "city": "Los Angeles",
    "zip": "90291",
    "state": "CA",
    "latitude": 33.985046,
    "longitude": -118.469483,
    "amount": 16000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Brickell Luxury Apartment",
    "headline": "Downtown Miami Living",
    "description": "Stay in the upscale Brickell neighborhood with access to top restaurants, bars, and shopping.",
    "address": "1234 Brickell Ave.",
    "city": "Miami",
    "zip": "33131",
    "state": "FL",
    "latitude": 25.761680,
    "longitude": -80.191790,
    "amount": 22000,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Sodo District Loft in Seattle",
    "headline": "Urban Industrial Aesthetic",
    "description": "This loft offers a unique industrial design with modern amenities in Seattle's Sodo district.",
    "address": "2020 1st Ave S.",
    "city": "Seattle",
    "zip": "98134",
    "state": "WA",
    "latitude": 47.592304,
    "longitude": -122.327292,
    "amount": 20000,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 1,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "Historic Austin Bungalow",
    "headline": "Charming Stay in East Austin",
    "description": "Relax in this historic bungalow, renovated with modern amenities and just a short bike ride to downtown Austin.",
    "address": "909 E. 6th St.",
    "city": "Austin",
    "zip": "78702",
    "state": "TX",
    "latitude": 30.265487,
    "longitude": -97.733664,
    "amount": 19000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 1
  },
  {
    "name": "Stylish SoHo Loft",
    "headline": "Experience Downtown NYC",
    "description": "A minimalist loft in the trendy SoHo district, surrounded by boutique shops and gourmet restaurants.",
    "address": "112 Mercer St.",
    "city": "New York",
    "zip": "10012",
    "state": "NY",
    "latitude": 40.7242,
    "longitude": -73.9979,
    "amount": 27000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 2
  },
  {
    "name": "Downtown LA Artsy Apartment",
    "headline": "Vibrant Artistic Ambience",
    "description": "Stay in the heart of LA's Art District with galleries and theaters right at your doorstep.",
    "address": "212 Arts St.",
    "city": "Los Angeles",
    "zip": "90013",
    "state": "CA",
    "latitude": 34.0454,
    "longitude": -118.2509,
    "amount": 23000,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 1,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "Miami Beachfront Condo",
    "headline": "Ocean Views and Sunny Skies",
    "description": "A luxury condo on Miami Beach, with pool access and a beachfront balcony.",
    "address": "580 Ocean Dr.",
    "city": "Miami",
    "zip": "33139",
    "state": "FL",
    "latitude": 25.7761,
    "longitude": -80.1341,
    "amount": 31000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 3,
    "bathrooms_count": 2
  },
  {
    "name": "Seattle Penthouse",
    "headline": "Views of Puget Sound",
    "description": "Experience downtown Seattle from this penthouse with a panoramic view of Puget Sound and the city skyline.",
    "address": "711 Bay St.",
    "city": "Seattle",
    "zip": "98121",
    "state": "WA",
    "latitude": 47.6130,
    "longitude": -122.3456,
    "amount": 29000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Austin's Riverside Cottage",
    "headline": "Peaceful Retreat in the City",
    "description": "A quaint cottage by the Colorado River, yet just minutes away from Austin's bustling nightlife.",
    "address": "1322 Riverside Ln.",
    "city": "Austin",
    "zip": "78704",
    "state": "TX",
    "latitude": 30.2486,
    "longitude": -97.7687,
    "amount": 21000,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 1,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "Garden District Mansion",
    "headline": "Historical Elegance in NOLA",
    "description": "Stay in a historic mansion in New Orleans' Garden District, surrounded by ancient oak trees and Southern charm.",
    "address": "1444 Magazine St.",
    "city": "New Orleans",
    "zip": "70130",
    "state": "LA",
    "latitude": 29.9427,
    "longitude": -90.0799,
    "amount": 32000,
    "currency": "USD",
    "guests_count": 6,
    "bedrooms_count": 4,
    "beds_count": 5,
    "bathrooms_count": 3
  },
  {
    "name": "Modern Condo in Downtown LA",
    "headline": "Skyline Views and Chic Decor",
    "description": "A sleek condo in the heart of downtown Los Angeles, offering floor-to-ceiling windows and modern amenities.",
    "address": "888 Hope St.",
    "city": "Los Angeles",
    "zip": "90017",
    "state": "CA",
    "latitude": 34.0478,
    "longitude": -118.2566,
    "amount": 22000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 2
  },
  {
    "name": "Coconut Grove Villa",
    "headline": "Tropical Oasis in Miami",
    "description": "A secluded villa in the historic Coconut Grove neighborhood, surrounded by lush gardens and close to the bay.",
    "address": "2201 S Bayshore Dr.",
    "city": "Miami",
    "zip": "33133",
    "state": "FL",
    "latitude": 25.7262,
    "longitude": -80.2381,
    "amount": 35000,
    "currency": "USD",
    "guests_count": 6,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 3
  },
  {
    "name": "Fremont Craftsman Home",
    "headline": "Cozy Stay in Vibrant Seattle",
    "description": "A charming craftsman home in the lively Fremont neighborhood, close to local shops and the Fremont Troll.",
    "address": "333 Troll Ave N.",
    "city": "Seattle",
    "zip": "98103",
    "state": "WA",
    "latitude": 47.6508,
    "longitude": -122.3473,
    "amount": 20000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 2
  },
  {
    "name": "Brooklyn Brownstone",
    "headline": "Chic Urban Living",
    "description": "Experience the authentic Brooklyn vibe in this renovated brownstone, just steps away from trendy bars and eateries.",
    "address": "220 Bedford Ave.",
    "city": "New York",
    "zip": "11211",
    "state": "NY",
    "latitude": 40.7183,
    "longitude": -73.9571,
    "amount": 28000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 2
  },


  {
    "name": "The Hollywood Suite",
    "headline": "Luxury in the Heart of LA",
    "description": "Enjoy the glitz and glam of Hollywood from this luxurious suite. Perfect for star-spotting!",
    "address": "123 Hollywood Blvd.",
    "city": "Los Angeles",
    "zip": "90028",
    "state": "CA",
    "latitude": 34.1016,
    "longitude": -118.3287,
    "amount": 35000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Greenwich Village Studio",
    "headline": "Classic New York Vibes",
    "description": "Experience the history and culture of NYC from this cozy studio in the heart of Greenwich Village.",
    "address": "234 Bleecker St.",
    "city": "New York",
    "zip": "10014",
    "state": "NY",
    "latitude": 40.7310,
    "longitude": -74.0020,
    "amount": 24000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Beachside Bungalow in Miami",
    "headline": "Sand, Sun, and Relaxation",
    "description": "Just steps away from the beach, this bungalow is your perfect sunny escape.",
    "address": "345 Ocean View Dr.",
    "city": "Miami",
    "zip": "33140",
    "state": "FL",
    "latitude": 25.8124,
    "longitude": -80.1228,
    "amount": 27000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 1
  },
  {
    "name": "Eclectic Loft in Downtown Austin",
    "headline": "Artsy Space Near 6th Street",
    "description": "Discover the vibrant culture of Austin from this uniquely designed downtown loft.",
    "address": "456 East Ave.",
    "city": "Austin",
    "zip": "78701",
    "state": "TX",
    "latitude": 30.2658,
    "longitude": -97.7452,
    "amount": 22000,
    "currency": "USD",
    "guests_count": 3,
    "bedrooms_count": 1,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "Space Needle Studio",
    "headline": "Iconic Views in Seattle",
    "description": "Watch the sunset over the Space Needle from the comfort of this modern Seattle studio.",
    "address": "567 Queen Anne Ave.",
    "city": "Seattle",
    "zip": "98109",
    "state": "WA",
    "latitude": 47.6253,
    "longitude": -122.3555,
    "amount": 23000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "Bourbon Street Balcony",
    "headline": "Experience New Orleans' Nightlife",
    "description": "Overlooking the lively Bourbon Street, this apartment lets you dive right into the heart of New Orleans.",
    "address": "678 Bourbon St.",
    "city": "New Orleans",
    "zip": "70116",
    "state": "LA",
    "latitude": 29.9584,
    "longitude": -90.0649,
    "amount": 26000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Downtown LA Sky Loft",
    "headline": "Spectacular City Views",
    "description": "A high-rise loft in DTLA with stunning views and modern amenities.",
    "address": "789 Cityscape Pl.",
    "city": "Los Angeles",
    "zip": "90015",
    "state": "CA",
    "latitude": 34.0423,
    "longitude": -118.2664,
    "amount": 29000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Brickell Bay Condo",
    "headline": "Elegant Stay in Miami's Financial District",
    "description": "A chic condo in the upscale Brickell area, with amenities like a rooftop pool and skyline views.",
    "address": "890 Brickell Bay Dr.",
    "city": "Miami",
    "zip": "33131",
    "state": "FL",
    "latitude": 25.7619,
    "longitude": -80.1918,
    "amount": 32000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 3,
    "bathrooms_count": 2
  },
  {
    "name": "Capitol Hill Chic Townhouse",
    "headline": "Elegance in the Heart of Seattle",
    "description": "Stay in a beautifully restored townhouse in the historic Capitol Hill neighborhood.",
    "address": "901 Broadway E.",
    "city": "Seattle",
    "zip": "98102",
    "state": "WA",
    "latitude": 47.6238,
    "longitude": -122.3205,
    "amount": 25000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Brooklyn Bridge Park Views",
    "headline": "Modern Living in DUMBO",
    "description": "Enjoy the mesmerizing views of the Brooklyn Bridge and Manhattan skyline from this stylish apartment.",
    "address": "1012 Water St.",
    "city": "New York",
    "zip": "11201",
    "state": "NY",
    "latitude": 40.7014,
    "longitude": -73.9895,
    "amount": 31000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 2
  },
  {
    "name": "Miami Beach Penthouse",
    "headline": "Ocean Views and Luxurious Living",
    "description": "Elevate your stay in this spacious penthouse overlooking the pristine beaches of Miami.",
    "address": "1123 Atlantic Blvd.",
    "city": "Miami",
    "zip": "33139",
    "state": "FL",
    "latitude": 25.7907,
    "longitude": -80.1300,
    "amount": 45000,
    "currency": "USD",
    "guests_count": 6,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 2
  },
  {
    "name": "Garden Loft in Brooklyn",
    "headline": "Urban Oasis in New York",
    "description": "Experience serenity in the heart of the city with our garden-view loft in the vibrant area of Brooklyn.",
    "address": "1234 Maple St.",
    "city": "New York",
    "zip": "11225",
    "state": "NY",
    "latitude": 40.6627,
    "longitude": -73.9624,
    "amount": 26000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 1
  },
  {
    "name": "Hillside Haven in Austin",
    "headline": "Secluded Stay Near Barton Springs",
    "description": "Relax in this quiet retreat, yet be moments away from Austin's famous springs and lively music scene.",
    "address": "1345 Hilltop Rd.",
    "city": "Austin",
    "zip": "78704",
    "state": "TX",
    "latitude": 30.2604,
    "longitude": -97.7586,
    "amount": 20000,
    "currency": "USD",
    "guests_count": 2,
    "bedrooms_count": 1,
    "beds_count": 1,
    "bathrooms_count": 1
  },
  {
    "name": "French Quarter Mansion",
    "headline": "Historical Elegance in NOLA",
    "description": "Dive into the rich history of New Orleans with a stay in this beautifully preserved mansion.",
    "address": "1456 Royal St.",
    "city": "New Orleans",
    "zip": "70130",
    "state": "LA",
    "latitude": 29.9589,
    "longitude": -90.0641,
    "amount": 32000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 4,
    "bathrooms_count": 3
  },
  {
    "name": "Downtown LA Artistic Loft",
    "headline": "Creative Space in the City Center",
    "description": "Be inspired by the artsy decor and vibrant surroundings of this unique DTLA loft.",
    "address": "1567 West Ave.",
    "city": "Los Angeles",
    "zip": "90017",
    "state": "CA",
    "latitude": 34.0522,
    "longitude": -118.2437,
    "amount": 28000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Rustic Cabin near Seattle",
    "headline": "Nature Retreat with Modern Comforts",
    "description": "Enjoy the best of both worlds with this rustic cabin that offers modern amenities and proximity to Seattle's attractions.",
    "address": "1678 Pine Rd.",
    "city": "Seattle",
    "zip": "98103",
    "state": "WA",
    "latitude": 47.6753,
    "longitude": -122.3475,
    "amount": 21000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 1
  },
  {
    "name": "Manhattan Skyview Suite",
    "headline": "New York Living at its Best",
    "description": "High above the city streets, this suite offers unparalleled views of the Manhattan skyline.",
    "address": "1789 Lexington Ave.",
    "city": "New York",
    "zip": "10035",
    "state": "NY",
    "latitude": 40.7957,
    "longitude": -73.9389,
    "amount": 40000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  },
  {
    "name": "Venice Beach Modern Villa",
    "headline": "Sunny SoCal Living",
    "description": "Steps away from the famous Venice Beach boardwalk, this villa provides the quintessential Southern California experience.",
    "address": "1890 Ocean Front Walk",
    "city": "Los Angeles",
    "zip": "90291",
    "state": "CA",
    "latitude": 33.9872,
    "longitude": -118.4702,
    "amount": 38000,
    "currency": "USD",
    "guests_count": 5,
    "bedrooms_count": 3,
    "beds_count": 3,
    "bathrooms_count": 3
  },
  {
    "name": "Seattle Harbor Apartment",
    "headline": "Picturesque Waterfront Views",
    "description": "Overlook the bustling harbor and enjoy the serene water views from this centrally located apartment.",
    "address": "2001 Harbor Ave.",
    "city": "Seattle",
    "zip": "98121",
    "state": "WA",
    "latitude": 47.6129,
    "longitude": -122.3451,
    "amount": 29000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 3,
    "bathrooms_count": 2
  },
  {
    "name": "Austin Lakeside Condo",
    "headline": "Tranquility in the Heart of the City",
    "description": "Experience lakeside living in Austin with easy access to the city's best attractions.",
    "address": "2112 Lake Blvd.",
    "city": "Austin",
    "zip": "78746",
    "state": "TX",
    "latitude": 30.2958,
    "longitude": -97.8272,
    "amount": 24000,
    "currency": "USD",
    "guests_count": 4,
    "bedrooms_count": 2,
    "beds_count": 2,
    "bathrooms_count": 2
  }
]
"""

_apartments =
  json_examples
  |> Jason.decode!()
  |> Enum.map(fn %{"name" => name, "address" => address, "zip" => zip} = attrs ->
    if apartment = Repo.get_by(Apartment, name: name, address: address, zip: zip) do
      {:ok, apartment} = Apartments.update_apartment(apartment, attrs)
      apartment
    else
      {:ok, apartment} = Apartments.create_apartment(attrs)
      apartment
    end
  end)
